//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_routine
    {
        public int rou_id { get; set; }
        public string rou_day { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<bool> IsMaths { get; set; }
        public string IsMathsSlot { get; set; }
        public Nullable<bool> IsEnglishLiterature { get; set; }
        public string IsEnglishLiteratureSlot { get; set; }
        public Nullable<bool> IsEnglishGrammar { get; set; }
        public string IsEnglishGrammarSlot { get; set; }
        public Nullable<bool> IsUrdu { get; set; }
        public string IsUrduSlot { get; set; }
        public Nullable<bool> IsIslamiyat { get; set; }
        public string IsIslamiyatSlot { get; set; }
        public Nullable<bool> IsScience { get; set; }
        public string IsScienceSlot { get; set; }
        public Nullable<bool> IsPhysics { get; set; }
        public string IsPhysicsSlot { get; set; }
        public Nullable<bool> IsChemistry { get; set; }
        public string IsChemistrySlot { get; set; }
        public Nullable<bool> IsComputer { get; set; }
        public string IsComputerSlot { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public string IsHistorySlot { get; set; }
        public Nullable<bool> IsGeography { get; set; }
        public string IsGeographySlot { get; set; }
    
        public virtual @class @class { get; set; }
    }
}
