//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.receptionists = new HashSet<receptionist>();
        }
    
        public int emp_ID { get; set; }
        public string emp_role { get; set; }
        public string emp_FIRST_NAME { get; set; }
        public string emp_LAST_NAME { get; set; }
        public string emp_ADDRESS { get; set; }
        public int emp_AGE { get; set; }
        public string emp_GENDER { get; set; }
        public string emp_PHONE_NUMBER { get; set; }
        public System.DateTime emp_DATE_TIME_EMPLOYMENT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receptionist> receptionists { get; set; }
    }
}
