//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.fees = new HashSet<fee>();
            this.results = new HashSet<result>();
        }
    
        public int std_id { get; set; }
        public string std_Fname { get; set; }
        public string std_Lname { get; set; }
        public string std_Fathername { get; set; }
        public string std_Mothername { get; set; }
        public string std_gender { get; set; }
        public string std_phone { get; set; }
        public string std_address { get; set; }
        public string std_email { get; set; }
        public string std_nationality { get; set; }
        public System.DateTime std_dob { get; set; }
        public System.DateTime std_doa { get; set; }
        public int std_age { get; set; }
        public string std_religion { get; set; }
        public Nullable<int> std_class_id { get; set; }
    
        public virtual @class @class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fee> fees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result> results { get; set; }
    }
}
