//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher
    {
        public int tea_id { get; set; }
        public string tea_Fname { get; set; }
        public string tea_Lname { get; set; }
        public string tea_gender { get; set; }
        public string tea_phone { get; set; }
        public string tea_address { get; set; }
        public string tea_email { get; set; }
        public int tea_age { get; set; }
        public string tea_religion { get; set; }
        public string tea_App_class { get; set; }
    }
}
